name: Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: crm-cluster
  ECS_SERVICE: session-service
  ECS_TASK_DEFINITION: session-task
  CONTAINER_NAME: session-service
  DOCKER_IMAGE: aledve/session-service
  DOCKER_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Verify AWS credentials
        id: verify-aws
        run: |
          if ! aws sts get-caller-identity; then
            echo "::error::Invalid AWS credentials"
            exit 1
          fi
          echo "✓ AWS credentials valid"

      - name: Login to Docker Hub
        if: steps.verify-aws.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.verify-aws.outcome == 'success'
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Get current task definition
        if: steps.verify-aws.outcome == 'success'
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --query 'taskDefinition' > task-definition.json

      - name: Update task definition
        if: steps.verify-aws.outcome == 'success'
        id: update-task-def
        run: |
          echo "Updating task definition with Neo4j configuration..."
          jq --arg IMAGE "${{ env.IMAGE_NAME }}" \
             --arg NAME "${{ env.CONTAINER_NAME }}" \
             --arg REDIS_IP "${{ secrets.REDIS_IP }}" \
             'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
             .containerDefinitions |= map(
               if .name == $NAME then 
                 .image = $IMAGE |
                 .environment += [
                   {
                     "name": "REDIS_IP",
                     "value": $REDIS_IP
                   }
                 ]
               else . end
             ) |
             if .executionRoleArn == null then del(.executionRoleArn) else . end' \
             task-definition.json > updated-task-definition.json
          echo "✓ Task definition updated with Neo4j configuration"

      - name: Register new task definition
        if: steps.verify-aws.outcome == 'success'
        run: |
          NEW_TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://updated-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "NEW_TASK_ARN=$NEW_TASK_ARN" >> $GITHUB_ENV

      - name: Update ECS service
        if: steps.verify-aws.outcome == 'success'
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.NEW_TASK_ARN }} \
            --force-new-deployment

      - name: Wait for deployment
        if: steps.verify-aws.outcome == 'success'
        run: |
          aws ecs wait services-stable \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }}
